name: "whisper"
backend: "python"
max_batch_size: 0

input [
  {
    name: "audio_signal"
    data_type: TYPE_FP32
    dims: [-1]
  },
  {
    name: "sample_rate"
    data_type: TYPE_INT32
    dims: [1]
  },
  {
    name: "language"
    data_type: TYPE_STRING
    dims: [1]
  },
  {
    name: "task"
    data_type: TYPE_STRING
    dims: [1]
  }
]

output [
  {
    name: "transcription"
    data_type: TYPE_STRING
    dims: [1]
  }
]

instance_group [
  {
    kind: KIND_CPU
    count: 2
  }
]

parameters: {
  key: "device"
  value: { string_value: "cpu" }
}

parameters: {
  key: "compute_type"
  value: { string_value: "int8" }
}
