name: "whisper"
backend: "python"
max_batch_size: 8

input [
  {
    name: "audio_signal"
    data_type: TYPE_FP32
    dims: [480000]
  },
  {
    name: "audio_len"
    data_type: TYPE_INT32
    dims: [1]
  },
  {
    name: "language"
    data_type: TYPE_STRING
    dims: [1]
  },
  {
    name: "task"
    data_type: TYPE_STRING
    dims: [1]
  }
]

output [
  {
    name: "transcription"
    data_type: TYPE_STRING
    dims: [1]
  }
]

instance_group [
  {
    kind: KIND_CPU
    count: 2
  }
]

dynamic_batching {
  preferred_batch_size: [2, 4, 8]
  max_queue_delay_microseconds: 50000
}
